import Foundation

extension L10n {
    static let overrideTables: [String: [String: String]] = [
        "zh-Hans": [
            "settings.language.title": "语言设置",
            "toolbar.tool.rectangle_select": "矩形选取",
            "toolbar.tool.circle_select": "圆形选取",
            "toolbar.tool.emoji": "表情与符号",
            "toolbar.tool.arrow": "箭头",
            "toolbar.tool.pen": "画笔",
            "toolbar.tool.mosaic": "马赛克",
            "toolbar.tool.text": "文字",
            "toolbar.tool.ocr_translate": "OCR 翻译",
            "toolbar.tool.ocr": "识别文字",
            "toolbar.tool.crop": "裁剪",
            "toolbar.action.undo": "撤销",
            "toolbar.action.save": "保存",
            "toolbar.action.pin": "钉图",
            "toolbar.action.share": "分享",
            "toolbar.action.cancel": "取消",
            "toolbar.action.confirm_copy": "截图并复制",
            "toolbar.action.start_capture": "开始截图",
            "capture.error.window_blocked": "窗口截图失败，可能被系统隐私设置阻止。",
            "capture.error.create_image": "无法创建图像，可能被系统隐私设置阻止。",
            "capture.error.empty_image": "截图为空。请在「系统设置 -> 隐私与安全性 -> 屏幕录制」中允许 StackShot。",
            "capture.alert.permission.title": "需要屏幕录制权限",
            "capture.alert.permission.body": "StackShot 使用该权限来执行截图、滚动长截图，以及对已捕获画面进行编辑、OCR、保存和导出。\n\n请按以下步骤操作：\n1. 点击「打开系统设置」\n2. 在「屏幕录制」列表中找到 StackShot，开启开关\n3. 若你已开启权限但仍提示，请先完全退出并重新打开 StackShot\n4. 重新按下快捷键 Shift + Command + A 即可截图",
            "capture.alert.permission.open_settings": "打开系统设置",
            "capture.alert.permission.later": "稍后",
            "capture.alert.failed.title": "截图失败",
            "capture.alert.ok": "好",
            "canvas.text.placeholder": "输入文字…",
            "launch_at_login.error_format": "设置开机启动失败：%@",
            "capture.window.untitled": "未命名窗口",
            "common.done": "完成",
            "common.close": "关闭",
            "common.live_preview": "实时预览",
            "compliance.privacy.menu_item": "隐私政策",
            "compliance.privacy.section_title": "隐私",
            "compliance.privacy.card_summary": "查看 StackShot 如何使用屏幕录制、辅助功能、剪贴板和本地文件访问权限。",
            "compliance.privacy.open_policy": "打开隐私政策",
            "compliance.screen_recording.title": "屏幕录制",
            "compliance.screen_recording.summary": "用于截图、滚动长截图，以及对已捕获画面执行 OCR/保存/导出。授权后若未立即生效，请完全退出并重新打开 StackShot。",
            "compliance.accessibility.title": "辅助功能（可选）",
            "compliance.accessibility.summary.granted": "已授权。StackShot 可以更准确地识别鼠标下的前台窗口。",
            "compliance.accessibility.summary.not_granted": "未授权时仍可手动框选截图，但悬停识别窗口会退回到屏幕快照匹配，精度可能降低。",
            "compliance.accessibility.button.open_settings": "打开辅助功能设置",
            "compliance.accessibility.button.request_access": "请求辅助功能权限",
            "compliance.screen_recording.open_settings": "打开屏幕录制设置",
            "compliance.privacy.window.intro": "StackShot 是一款本地截图工具。我们尽量只在用户明确触发的情况下访问系统权限，并优先在设备本地处理图像内容。",
            "compliance.privacy.paragraph.1": "1. 屏幕录制：用于截图、滚动截图和对已捕获画面进行后续编辑。未经你的操作，StackShot 不会自动开始录屏。",
            "compliance.privacy.paragraph.2": "2. 辅助功能：仅用于更准确识别鼠标下的前台窗口。未授予时，应用仍可使用手动框选截图，但窗口悬停识别精度可能降低。",
            "compliance.privacy.paragraph.3": "3. 剪贴板与文件：只有在你明确执行复制、分享或保存时，StackShot 才会把图像或文字写入剪贴板，或导出到你选择的位置。",
            "compliance.privacy.paragraph.4": "4. OCR 内置翻译：当你点击 OCR 翻译时，StackShot 会先在本机识别文字，再通过 Apple 官方 Translation 框架在应用内完成翻译（需 macOS 15 或更高版本）。根据 Apple 的框架说明，Apple 可能收集不含原文内容的使用与性能指标，例如 App Bundle ID 与源/目标语言。",
            "compliance.privacy.paragraph.5": "5. 本地处理：截图编辑、窗口识别、OCR 和大部分图像处理都在本机完成。应用不包含远程上传截图内容的网络同步逻辑。",
            "compliance.privacy.paragraph.6": "6. 偏好设置：语言、Dock 显示和快捷键等设置只保存在本机的应用偏好中，用于恢复你的使用习惯。",
            "compliance.privacy.window.footer": "如需在 App Store 中提交版本，还需要在 App Store Connect 中填写外部隐私政策链接和隐私营养标签。",
            "scroll.flow.hud.watching": "正在监控滚动…",
            "scroll.flow.hud.hint": "把鼠标移到目标窗口慢慢滚动；点击「完成」或「取消」结束。",
            "scroll.flow.hud.frames_format": "已拼接 %3$dpx · 帧 %1$d/%2$d",
            "scroll.flow.result.title": "滚动长截图",
            "scroll.flow.result.save": "保存到本地…",
            "scroll.flow.result.copy": "复制到剪贴板",
            "scroll.flow.result.copied": "已复制",
            "scroll.flow.result.empty.title": "未捕获到滚动",
            "scroll.flow.result.empty.hint": "请在选区内的窗口中滚动后再次尝试。",
            "scroll.flow.save.default_name": "滚动长截图",
            "editor.window.title": "编辑截图",
            "editor.save.failed.title": "保存失败",
            "editor.save.failed.message_prefix": "无法保存图片，请重试。",
            "editor.export.format_label": "格式：",
            "editor.ocr.empty.title": "未识别到文字",
            "editor.ocr.empty.message": "图片中没有可识别的文字。",
            "editor.ocr.done.title": "文字识别完成",
            "editor.ocr.done.message_format": "已识别 %d 个字符并复制到剪贴板。",
            "editor.ocr.translatable_empty.message": "图片中没有可翻译的文字。",
            "editor.ocr.translate.in_progress": "正在翻译…",
            "editor.ocr.translate.failed.title": "翻译失败",
            "editor.ocr.translate.failed.message_prefix": "无法发起翻译：",
            "editor.ocr.translate.unavailable": "内置翻译需要 macOS 15 或更高版本，并使用 Apple 官方 Translation 框架。当前系统不支持时，可先使用“识别文字”。",
            "editor.export.read_image_data_failed": "无法读取图像数据。",
            "editor.export.unsupported_type": "不支持该文件格式。",
            "editor.export.write_failed": "系统写入文件失败。",
            "editor.tool.rectangle": "矩形标注",
            "editor.tool.circle": "圆形标注",
            "editor.tool.ocr_translate": "识别并翻译",
            "editor.tool.scroll_capture": "滚动截图",
            "editor.action.adjust_selection": "调整选区",
            "editor.action.confirm_copy": "确认并复制",
            "editor.emoji_picker.title": "Emoji",
            "editor.text_style.font": "字体",
            "editor.text_style.size": "字号",
            "editor.mosaic.radius": "半径",
        ],
        "zh-Hant": [
            "settings.language.title": "語言設定",
            "toolbar.tool.rectangle_select": "矩形選取",
            "toolbar.tool.circle_select": "圓形選取",
            "toolbar.tool.emoji": "表情與符號",
            "toolbar.tool.arrow": "箭頭",
            "toolbar.tool.pen": "畫筆",
            "toolbar.tool.mosaic": "馬賽克",
            "toolbar.tool.text": "文字",
            "toolbar.tool.ocr_translate": "OCR 翻譯",
            "toolbar.tool.ocr": "辨識文字",
            "toolbar.tool.crop": "裁剪",
            "toolbar.action.undo": "復原",
            "toolbar.action.save": "儲存",
            "toolbar.action.pin": "釘圖",
            "toolbar.action.share": "分享",
            "toolbar.action.cancel": "取消",
            "toolbar.action.confirm_copy": "截圖並複製",
            "toolbar.action.start_capture": "開始截圖",
            "capture.error.window_blocked": "視窗截圖失敗，可能被系統隱私設定阻擋。",
            "capture.error.create_image": "無法建立圖像，可能被系統隱私設定阻擋。",
            "capture.error.empty_image": "截圖為空。請在「系統設定 -> 隱私權與安全性 -> 螢幕錄製」中允許 StackShot。",
            "capture.alert.permission.title": "需要螢幕錄製權限",
            "capture.alert.permission.body": "StackShot 使用此權限來執行截圖、捲動長截圖，以及對已擷取畫面進行編輯、OCR、儲存與匯出。\n\n請依下列步驟操作：\n1. 點擊「打開系統設定」\n2. 在「螢幕錄製」清單中找到 StackShot，開啟開關\n3. 若已開啟仍持續提示，請先完整結束並重新開啟 StackShot\n4. 再次按下 Shift + Command + A 進行截圖",
            "capture.alert.permission.open_settings": "打開系統設定",
            "capture.alert.permission.later": "稍後",
            "capture.alert.failed.title": "截圖失敗",
            "capture.alert.ok": "好",
            "canvas.text.placeholder": "輸入文字…",
            "launch_at_login.error_format": "設定登入時啟動失敗：%@",
            "capture.window.untitled": "未命名視窗",
            "common.done": "完成",
            "common.close": "關閉",
            "common.live_preview": "即時預覽",
            "compliance.privacy.menu_item": "隱私政策",
            "compliance.privacy.section_title": "隱私",
            "compliance.privacy.card_summary": "查看 StackShot 如何使用螢幕錄製、輔助使用、剪貼簿和本機檔案存取權限。",
            "compliance.privacy.open_policy": "打開隱私政策",
            "compliance.screen_recording.title": "螢幕錄製",
            "compliance.screen_recording.summary": "用於截圖、捲動長截圖，以及對已擷取畫面執行 OCR／儲存／匯出。授權後若未立即生效，請完全結束並重新開啟 StackShot。",
            "compliance.accessibility.title": "輔助使用（選用）",
            "compliance.accessibility.summary.granted": "已授權。StackShot 可以更準確地辨識游標下的前景視窗。",
            "compliance.accessibility.summary.not_granted": "未授權時仍可手動框選截圖，但懸停辨識視窗會退回到螢幕快照比對，精度可能較低。",
            "compliance.accessibility.button.open_settings": "打開輔助使用設定",
            "compliance.accessibility.button.request_access": "要求輔助使用權限",
            "compliance.screen_recording.open_settings": "打開螢幕錄製設定",
            "compliance.privacy.window.intro": "StackShot 是一款本機截圖工具。我們盡量只在使用者明確觸發時存取系統權限，並優先在裝置本機處理影像內容。",
            "compliance.privacy.paragraph.1": "1. 螢幕錄製：用於截圖、捲動截圖以及對已擷取畫面進行後續編輯。未經你的操作，StackShot 不會自動開始錄屏。",
            "compliance.privacy.paragraph.2": "2. 輔助使用：僅用於更準確辨識游標下的前景視窗。未授權時，應用仍可使用手動框選截圖，但視窗懸停辨識精度可能降低。",
            "compliance.privacy.paragraph.3": "3. 剪貼簿與檔案：只有在你明確執行複製、分享或儲存時，StackShot 才會把影像或文字寫入剪貼簿，或匯出到你選擇的位置。",
            "compliance.privacy.paragraph.4": "4. OCR 內建翻譯：當你點擊 OCR 翻譯時，StackShot 會先在本機辨識文字，再透過 Apple 官方 Translation 框架在 App 內完成翻譯（需 macOS 15 或以上版本）。依 Apple 框架說明，Apple 可能收集不包含原文內容的使用與效能指標，例如 App Bundle ID 與來源／目標語言。",
            "compliance.privacy.paragraph.5": "5. 本機處理：截圖編輯、視窗辨識、OCR 和大部分影像處理都在本機完成。應用不包含遠端上傳截圖內容的網路同步邏輯。",
            "compliance.privacy.paragraph.6": "6. 偏好設定：語言、Dock 顯示和快捷鍵等設定只保存在本機的應用偏好中，用於還原你的使用習慣。",
            "compliance.privacy.window.footer": "如需在 App Store 中提交版本，仍需在 App Store Connect 中填寫外部隱私政策連結與隱私營養標籤。",
            "scroll.flow.hud.watching": "正在監控捲動…",
            "scroll.flow.hud.hint": "把滑鼠移到目標視窗慢慢捲動；點擊「完成」或「取消」結束。",
            "scroll.flow.hud.frames_format": "已拼接 %3$dpx · 幀 %1$d/%2$d",
            "scroll.flow.result.title": "捲動長截圖",
            "scroll.flow.result.save": "儲存到本機…",
            "scroll.flow.result.copy": "複製到剪貼簿",
            "scroll.flow.result.copied": "已複製",
            "scroll.flow.result.empty.title": "未擷取到捲動",
            "scroll.flow.result.empty.hint": "請在選區內的視窗中捲動後再次嘗試。",
            "scroll.flow.save.default_name": "捲動長截圖",
            "editor.window.title": "編輯截圖",
            "editor.save.failed.title": "儲存失敗",
            "editor.save.failed.message_prefix": "無法儲存圖片，請再試一次。",
            "editor.export.format_label": "格式：",
            "editor.ocr.empty.title": "未辨識到文字",
            "editor.ocr.empty.message": "圖片中沒有可辨識的文字。",
            "editor.ocr.done.title": "文字辨識完成",
            "editor.ocr.done.message_format": "已辨識 %d 個字元並複製到剪貼簿。",
            "editor.ocr.translatable_empty.message": "圖片中沒有可翻譯的文字。",
            "editor.ocr.translate.in_progress": "翻譯中…",
            "editor.ocr.translate.failed.title": "翻譯失敗",
            "editor.ocr.translate.failed.message_prefix": "無法啟動翻譯：",
            "editor.ocr.translate.unavailable": "內建翻譯需要 macOS 15 或以上版本，並使用 Apple 官方 Translation 框架。若目前系統不支援，可先使用「辨識文字」。",
            "editor.export.read_image_data_failed": "無法讀取圖像資料。",
            "editor.export.unsupported_type": "不支援此檔案格式。",
            "editor.export.write_failed": "系統寫入檔案失敗。",
            "editor.tool.rectangle": "矩形標註",
            "editor.tool.circle": "圓形標註",
            "editor.tool.ocr_translate": "辨識並翻譯",
            "editor.tool.scroll_capture": "捲動截圖",
            "editor.action.adjust_selection": "調整選區",
            "editor.action.confirm_copy": "確認並複製",
            "editor.emoji_picker.title": "Emoji",
            "editor.text_style.font": "字體",
            "editor.text_style.size": "字號",
            "editor.mosaic.radius": "半徑",
        ],
        "ja": [
            "settings.language.title": "言語設定",
            "toolbar.tool.rectangle_select": "四角形選択",
            "toolbar.tool.circle_select": "円形選択",
            "toolbar.tool.emoji": "絵文字と記号",
            "toolbar.tool.arrow": "矢印",
            "toolbar.tool.pen": "ペン",
            "toolbar.tool.mosaic": "モザイク",
            "toolbar.tool.text": "テキスト",
            "toolbar.tool.ocr_translate": "OCR 翻訳",
            "toolbar.tool.ocr": "テキスト認識",
            "toolbar.tool.crop": "切り取り",
            "toolbar.action.undo": "元に戻す",
            "toolbar.action.save": "保存",
            "toolbar.action.pin": "ピン留め",
            "toolbar.action.share": "共有",
            "toolbar.action.cancel": "キャンセル",
            "toolbar.action.confirm_copy": "キャプチャしてコピー",
            "toolbar.action.start_capture": "キャプチャ開始",
            "capture.error.window_blocked": "ウインドウのキャプチャに失敗しました。システムのプライバシー設定でブロックされている可能性があります。",
            "capture.error.create_image": "画像を作成できませんでした。システムのプライバシー設定でブロックされている可能性があります。",
            "capture.error.empty_image": "キャプチャ画像が空です。システム設定 -> プライバシーとセキュリティ -> 画面収録 で StackShot を許可してください。",
            "capture.alert.permission.title": "画面収録の権限が必要です",
            "capture.alert.permission.body": "StackShot はこの権限をスクリーンショット、スクロールキャプチャ、および取得済み画像の編集・OCR・保存・書き出しに使用します。\n\n次の手順で設定してください：\n1. 「システム設定を開く」をクリック\n2. 「画面収録」一覧で StackShot をオンにする\n3. すでにオンでも表示される場合は StackShot を完全終了して再起動する\n4. Shift + Command + A を再度押してキャプチャする",
            "capture.alert.permission.open_settings": "システム設定を開く",
            "capture.alert.permission.later": "後で",
            "capture.alert.failed.title": "キャプチャ失敗",
            "capture.alert.ok": "OK",
            "canvas.text.placeholder": "テキストを入力…",
            "launch_at_login.error_format": "ログイン時に起動の設定に失敗しました: %@",
            "capture.window.untitled": "無題のウインドウ",
            "common.done": "完了",
            "common.close": "閉じる",
            "common.live_preview": "ライブプレビュー",
            "compliance.privacy.menu_item": "プライバシーポリシー",
            "compliance.privacy.section_title": "プライバシー",
            "compliance.privacy.card_summary": "StackShot が画面収録、アクセシビリティ、クリップボード、ローカルファイルアクセスをどう扱うか確認できます。",
            "compliance.privacy.open_policy": "プライバシーポリシーを開く",
            "compliance.screen_recording.title": "画面収録",
            "compliance.screen_recording.summary": "スクリーンショット、スクロールキャプチャ、取得済み画像の OCR / 保存 / 書き出しに使用します。許可後に反映されない場合は StackShot を完全終了して再起動してください。",
            "compliance.accessibility.title": "アクセシビリティ（任意）",
            "compliance.accessibility.summary.granted": "許可済みです。StackShot はポインタ下の最前面ウィンドウをより正確に判定できます。",
            "compliance.accessibility.summary.not_granted": "未許可でも手動範囲選択は使えますが、ホバー時のウィンドウ判定は画面スナップショット照合にフォールバックするため精度が下がる場合があります。",
            "compliance.accessibility.button.open_settings": "アクセシビリティ設定を開く",
            "compliance.accessibility.button.request_access": "アクセシビリティ権限を要求",
            "compliance.screen_recording.open_settings": "画面収録設定を開く",
            "compliance.privacy.window.intro": "StackShot はローカル処理中心のスクリーンショットツールです。権限はユーザーの明示操作時にのみ使い、画像処理はできる限りデバイス上で行います。",
            "compliance.privacy.paragraph.1": "1. 画面収録: スクリーンショット、スクロールキャプチャ、取得済み画像の編集にのみ使用します。あなたが操作しない限り、自動で収録を開始しません。",
            "compliance.privacy.paragraph.2": "2. アクセシビリティ: ポインタ下の最前面ウィンドウをより正確に識別するためだけに使用します。許可しなくても手動範囲選択は利用できますが、ホバー判定の精度は下がる場合があります。",
            "compliance.privacy.paragraph.3": "3. クリップボードとファイル: 画像や文字をクリップボードへ書き込んだり、選択した場所へ保存したりするのは、コピー・共有・保存をあなたが明示的に実行したときだけです。",
            "compliance.privacy.paragraph.4": "4. OCR 内蔵翻訳: OCR 翻訳を実行すると、StackShot はまずデバイス上で文字を認識し、Apple の公開 Translation フレームワークを使ってアプリ内で翻訳します（macOS 15 以降が必要です）。Apple の説明によると、Apple は元のテキスト内容を含まない利用状況や性能指標（アプリの Bundle ID、元言語／対象言語など）を収集する場合があります。",
            "compliance.privacy.paragraph.5": "5. ローカル処理: スクリーンショット編集、ウィンドウ判定、OCR、ほとんどの画像処理はデバイス上で完結します。取得した画像を自動送信する同期機能は含みません。",
            "compliance.privacy.paragraph.6": "6. 設定情報: 言語、Dock 表示、ショートカットなどの設定は、この Mac 上のアプリ設定にのみ保存され、利用環境の復元に使われます。",
            "compliance.privacy.window.footer": "App Store 提出時は、App Store Connect 側でも外部プライバシーポリシー URL とプライバシー情報を設定してください。",
            "scroll.flow.hud.watching": "スクロールを監視中…",
            "scroll.flow.hud.hint": "対象ウィンドウにカーソルを移動してスクロール。「完了」または「キャンセル」で停止。",
            "scroll.flow.hud.frames_format": "縫合 %3$dpx · フレーム %1$d/%2$d",
            "scroll.flow.result.title": "スクロール長尺スクリーンショット",
            "scroll.flow.result.save": "ローカルに保存…",
            "scroll.flow.result.copy": "クリップボードにコピー",
            "scroll.flow.result.copied": "コピーしました",
            "scroll.flow.result.empty.title": "スクロールを取得できませんでした",
            "scroll.flow.result.empty.hint": "選択領域内のウィンドウでスクロールしてから再試行してください。",
            "scroll.flow.save.default_name": "スクロール長尺",
            "editor.window.title": "スクリーンショットを編集",
            "editor.save.failed.title": "保存に失敗しました",
            "editor.save.failed.message_prefix": "画像を保存できませんでした。もう一度お試しください。",
            "editor.export.format_label": "形式:",
            "editor.ocr.empty.title": "テキストが検出されませんでした",
            "editor.ocr.empty.message": "画像に認識可能なテキストが見つかりませんでした。",
            "editor.ocr.done.title": "テキスト認識完了",
            "editor.ocr.done.message_format": "%d 文字を認識しクリップボードにコピーしました。",
            "editor.ocr.translatable_empty.message": "画像に翻訳可能なテキストが見つかりませんでした。",
            "editor.ocr.translate.in_progress": "翻訳中…",
            "editor.ocr.translate.failed.title": "翻訳に失敗しました",
            "editor.ocr.translate.failed.message_prefix": "翻訳を開始できませんでした：",
            "editor.ocr.translate.unavailable": "内蔵翻訳は macOS 15 以降で利用でき、Apple の公開 Translation フレームワークを使用します。現在のシステムで利用できない場合は、先に「テキスト認識」を使ってください。",
            "editor.export.read_image_data_failed": "画像データを読み取れませんでした。",
            "editor.export.unsupported_type": "このファイル形式はサポートされていません。",
            "editor.export.write_failed": "ファイルの書き込みに失敗しました。",
            "editor.tool.rectangle": "四角形",
            "editor.tool.circle": "円形",
            "editor.tool.ocr_translate": "認識して翻訳",
            "editor.tool.scroll_capture": "スクロールキャプチャ",
            "editor.action.adjust_selection": "選択範囲を調整",
            "editor.action.confirm_copy": "確認してコピー",
            "editor.emoji_picker.title": "Emoji",
            "editor.text_style.font": "フォント",
            "editor.text_style.size": "サイズ",
            "editor.mosaic.radius": "半径",
        ],
    ]
}